# DATABASE AND DATABASE CREDENTIAL
spring.datasource.url = jdbc:mysql://sql12.freesqldatabase.com:3306/sql12620970?useSSL=false
spring.datasource.username = sql12620970
spring.datasource.password = sWjSdDUI4N

# The SQL dialect defines what types of database is in use so that it can generate appropriate statements.
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

# Allows to update the database schema based on java entities found in the project
spring.jpa.hibernate.ddl-auto = update

#User define keyword/secret that will be use to generate JWT's
jwt.secret = "jsonwebtoken"